### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by DaveInTO** [handsomecode/InteractiveSideMenu#1]
Possible to disable rotation on all the sub pages except 1?
I've tried many of the solutions on SO, for NavBar UI, but they don't seem to work with this.

Thanks,
Dave

**Comment by AndreyArzhannikov** [comment]
Hi @DaveInTO 

Unfortunately, at the moment current version of the library doesn't support rotation feature. I'm going to implement it in next release.

Thanks!

**Comment by douglas-srs** [comment]
Can't wait for rotation support :D

**Comment by douglas-srs** [comment]
I managed to get some kind of rotation support by adding this to MenuViewController.swift

`func delay(seconds: Double, completion:@escaping ()->()) {
        let popTime = DispatchTime.now() + Double(Int64( Double(NSEC_PER_SEC) * seconds )) / Double(NSEC_PER_SEC)
        DispatchQueue.main.asyncAfter(deadline: popTime) {
            completion()
        }
    }
    
    open override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        self.menuContainerViewController?.hideMenu()
        super.viewWillTransition(to: size, with: coordinator)
        self.delay(seconds: 0.5){
            self.menuContainerViewController?.showMenu()
        }
    }`

**Comment by AndreyArzhannikov** [comment]
@douglas-srs Thanks for sharing some workaround for rotation feature!

**Comment by okonor** [comment]
The rotation feature is available in [new Side Menu version](https://github.com/handsomecode/InteractiveSideMenu/releases/tag/2.0). You can try it!
