### ISSUE TITLE
How can showmenu inside of navigation page ?

### ISSUE THREAD

**Issue by ketulbshah** [handsomecode/InteractiveSideMenu#10]
Hi,

I have 5 pages inside side menu..
One of that is HomePage.

My flow is like this. 

HomePage (tableview) >> CategoryPage

Now From this category page when click button for showmenu getting error like bellow
Could not cast value of type 'UINavigationController' (0x2ee9244) to 'InteractiveSideMenu.MenuContainerViewController' (0x544ab0). 

Kindly provide solution for this.

**Comment by AndreyArzhannikov** [comment]
@ketulbshah Hi!

Unfortunately, there is no support of `UINavigationController` at the moment, but you can use some workaround. You can see more details [here](https://github.com/handsomecode/InteractiveSideMenu/issues/3).

Thanks for your question!
