### ISSUE TITLE
Storyboard to Nib

### ISSUE THREAD

**Issue by thundenilla** [handsomecode/InteractiveSideMenu#11]
Hi i'm still new in IOS development. a quick question, is there anyway to implement this into Nib? Since most of my modules I'm using Nib, so for me to implement this using storyboard very confusing for me. Thank you.

**Comment by AndreyArzhannikov** [comment]
Hi @thundenilla Hi!
Yes, sure!  it's possible to use Nib files. So the library doesn't use storyboard usage. 
You just need to provide `menuViewController` and `contentViewControllers` instances to use the library. So you can create it any way you want. 

Thanks for your question!
