### ISSUE TITLE
iOS 13 support

### ISSUE THREAD

**Issue by yberdnikov** [handsomecode/InteractiveSideMenu#112]
Right now when you select new controller, it shows black screen. Same code works on iOS 12 and earlier versions.

**Comment by iosMentalist** [comment]
Same here. I also tried the forked repos that support swift 5.0 but same result.

**Comment by kiwiswift** [comment]
Try setting the **modalPresentationStyle** of menu viewController to **fullScreen** as below. It should solve the problem.

```swift
    override func viewDidLoad() {
        super.viewDidLoad()

        let screenSize: CGRect = UIScreen.main.bounds
        self.transitionOptions = TransitionOptions(duration: 0.4, visibleContentWidth: screenSize.width / 6)

        // Instantiate menu view controller by identifier
        self.menuViewController = SampleMenuViewController.storyboardViewController()
        self.menuViewController.modalPresentationStyle = .fullScreen
        
        // Gather content items controllers
        self.contentViewControllers = contentControllers()

        // Select initial content controller. It's needed even if the first view controller should be selected.
        self.selectContentViewController(contentViewControllers.first!)

        self.currentItemOptions.cornerRadius = 10.0
    }
`

**Comment by kanagudurai** [comment]
> Try setting the **modalPresentationStyle** of menu viewController to **fullScreen** as below. It should solve the problem.
> 
> ```swift
>     override func viewDidLoad() {
>         super.viewDidLoad()
> 
>         let screenSize: CGRect = UIScreen.main.bounds
>         self.transitionOptions = TransitionOptions(duration: 0.4, visibleContentWidth: screenSize.width / 6)
> 
>         // Instantiate menu view controller by identifier
>         self.menuViewController = SampleMenuViewController.storyboardViewController()
>         self.menuViewController.modalPresentationStyle = .fullScreen
>         
>         // Gather content items controllers
>         self.contentViewControllers = contentControllers()
> 
>         // Select initial content controller. It's needed even if the first view controller should be selected.
>         self.selectContentViewController(contentViewControllers.first!)
> 
>         self.currentItemOptions.cornerRadius = 10.0
>     }
> `
> ```

Solved my problem. Thank you so much

**Comment by Kaustubh2018** [comment]
Awsome Support By you guys.. Thank you guys

**Comment by iosMentalist** [comment]
> Try setting the **modalPresentationStyle** of menu viewController to **fullScreen** as below. It should solve the problem.
> 
> ```swift
>     override func viewDidLoad() {
>         super.viewDidLoad()
> 
>         let screenSize: CGRect = UIScreen.main.bounds
>         self.transitionOptions = TransitionOptions(duration: 0.4, visibleContentWidth: screenSize.width / 6)
> 
>         // Instantiate menu view controller by identifier
>         self.menuViewController = SampleMenuViewController.storyboardViewController()
>         self.menuViewController.modalPresentationStyle = .fullScreen
>         
>         // Gather content items controllers
>         self.contentViewControllers = contentControllers()
> 
>         // Select initial content controller. It's needed even if the first view controller should be selected.
>         self.selectContentViewController(contentViewControllers.first!)
> 
>         self.currentItemOptions.cornerRadius = 10.0
>     }
> `
> ```
did u use the latest repo?

**Comment by fatihkan** [comment]
Thank you. If you change this code only need this code line self.menuViewController.modalPresentationStyle = .fullScreen

**Comment by numanayhan** [comment]
Thanks bro  .fullScreen is fixed this isuues

**Comment by doitwithdk** [comment]
Perfect fix. @handsomecode pls accept the PR
