### ISSUE TITLE
Screen becames black

### ISSUE THREAD

**Issue by maryanakotova** [handsomecode/InteractiveSideMenu#115]
Screen of presented ViewController became black with some delay after presenting (when selecting any item from menu). 
Tested on iOS 13.2, iPhoneX, SE.

**Comment by gunjan33** [comment]
Try setting the **modalPresentationStyle** of menu viewController to **fullScreen** as below. It should solve the problem.
`self.menuViewController.modalPresentationStyle = .fullScreen`

For more details please refer [https://github.com/handsomecode/InteractiveSideMenu/issues/112#issuecomment-533745269](url)

**Comment by maryanakotova** [comment]
Thank you!
