### ISSUE TITLE
Lateral menu cover current view

### ISSUE THREAD

**Issue by guedesbgeorge** [handsomecode/InteractiveSideMenu#12]
Hi!
I have a lateral menu on the left side of my screen. Right now, when I tap the menu button, the lateral menu comes from the left side and pushes my current view to the right. 
I was wondering if it's possible to have the lateral menu covers my current view instead of pushing to the right. Also, if it isn't, is there any workaround that I can do to achieve that?

Thanks a lot!
And thanks for this great library too!

**Comment by okonor** [comment]
Hi @guedesbgeorge,

Unfortunately, our library doesn't have this type of customization. And it's not our focus right now.

But you can update transition animation in the library to get desired behavior. Take a look into `startTransition`, `updateTransition` and `finishTransition` methods of `MenuAnimator.swift`.
Feel free to ask any questions, concerning transition implementation.

Thank you for your question. 
If you really need this feature, please, send pull request to us, we will consider this idea.
