### ISSUE TITLE
Spring Animation parameters customization

### ISSUE THREAD

**Issue by someyura** [handsomecode/InteractiveSideMenu#17]
On the main page, you've written that your menu supports "spring animation with params customization". On the same page at the example code, there is no a single word about how to do that. And when I'm looking into the "Sample Code" for more details, I see the very same example code that doesn't clarify spring customization.

I've looked into your source code and tried to do it in the same way, but it doesn't work because `'SpringParams' initializer is inaccessible due to 'internal' protection level`.

I'm sorry if I get something wrong or missed something, but please, can you help me to deal with spring animation parameters customization?

**Comment by okonor** [comment]
Huge thanks, Yury, for your question. 

You are doing everything right. It's the library issue. The new version will be released in the coming days. The bug will be fixed there.

Thank you very much again. Please, feel free ask more questions or send pull-requests to us.

**Comment by okonor** [comment]
This issue has been fixed in version 2.0 - https://github.com/handsomecode/InteractiveSideMenu/releases/tag/2.0.

Thanks again for your comment.
