### ISSUE TITLE
NavigationViewController support

### ISSUE THREAD

**Issue by Recouse** [handsomecode/InteractiveSideMenu#21]
Please add NavigationViewController support.

**Comment by phr85** [comment]
I had same problem.
Solution: Create Subclass of UINavigationController and add SideMenuItemContent protocol.

In your view controller:
` let navController = navigationController as! YourCustomNavigationViewController
        navController.showSideMenu()`

Hope this helps.

**Comment by Recouse** [comment]
I can't create subclass of UINavigationController and add MenuItemContentViewController protocol.

**Comment by Recouse** [comment]
I've done as shown here https://github.com/handsomecode/InteractiveSideMenu/issues/3#issuecomment-293832998

But I can't use buttons to open menu:
```swift
Could not cast value of type 'TestProject.AppNavigationController' (0x10e7a8368) to 'InteractiveSideMenu.MenuContainerViewController' (0x10eac7d20).
(lldb) 
```

**Comment by Recouse** [comment]
I updated to the latest version 2.0 where added NavigationController support.
All works.
