### ISSUE TITLE
showSideMenu() no response

### ISSUE THREAD

**Issue by Recouse** [handsomecode/InteractiveSideMenu#22]
In `SideMenuItemContent` added this code:
```swift
func openMenu() {
    showSideMenu()
}
```
and:
```swift
menuButton.addTarget(self, action: #selector(openMenu), for: .touchUpInside)
```

But when I click the button there is no response.

**Comment by AndreyArzhannikov** [comment]
Hi, @Recouse 

Thanks for your question!

Please make sure that you already added your viewController that implements  `SideMenuItemContent` protocol to an array of `contentViewControllers` within your container VC.

Here's an [example](https://github.com/handsomecode/InteractiveSideMenu/blob/master/Sample/Sample/HostViewController.swift#L48).

Let us know if it doesn't help you.

**Comment by Recouse** [comment]
Yes, I've added my viewController to an array of `contentViewControllers`. In that list my UINavigationController which connected with viewController. In array of `contentViewControllers` my UINavigationController's id.

**Comment by AndreyArzhannikov** [comment]
@Recouse Unfortunately, We weren't able to reproduce this issue. 
So, could you provide more detailed information about your case? It would be great to see some code examples.

**Comment by Recouse** [comment]
Here is an example https://www.dropbox.com/s/d38804nrngl0lo8/TestApp.zip?dl=1

**Comment by okonor** [comment]
Hi Firdavs,

UINavigationViewController should adopt `SideMenuItemContent` protocol directly, not any other connected controllers:

```swift
import UIKit
import InteractiveSideMenu

class NavigationViewController: UINavigationController, SideMenuItemContent {

}

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        title = "Test App"
    }

    @IBAction func openMenu(_ sender: Any) {
        if let navigationViewController = self.navigationController as? SideMenuItemContent {
            navigationViewController.showSideMenu()
        }
    }
}
```

I've updated the code of your `ViewController` file and now menu opens.

Hope, it'll help you.

**Comment by Recouse** [comment]
@okonor Now it works. Thanks.
