### ISSUE TITLE
have a navigationviewcontroller support ?

### ISSUE THREAD

**Issue by cagricolak** [handsomecode/InteractiveSideMenu#3]
i want to use navigationviewcontroller on my one of view controller instantiate from your api but i getting this error.
_Could not cast value of type 'Mosyo.EntriesController' to 'UINavigationController'_

```
let nav = segue.destination as! UINavigationController
let productListController = nav.topViewController as! EntriesController
      
let cell = sender as! UICollectionViewCell
let indexPath = self.collectionView!.indexPath(for: cell)
```

how can i fix this ?

thanks.

**Comment by okonor** [comment]
Hi @cagricolak, 

Now the library doesn't support working with `UINavigationController`.

You can use workaround to add NavigationController to your application. You should create `NavigationViewController` that is an inheritor of `MenuItemContentViewController` and then to add actual UINavigationController as a child view controller.

Here is an example: 

```swift
class NavigationViewController: MenuItemContentViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let innerNavigationController = self.storyboard!.instantiateViewController(withIdentifier: "InnerNavigationController") as! UINavigationController

        self.addChildViewController(innerNavigationController)
        self.view.addSubview(innerNavigationController.view)
    }
}
```

Thank you for your question. Adding support of `UITabBarController` and `UINavigationController` is planned in coming version. Please, feel free to send us pull requests!

**Comment by schulz89sp** [comment]
Hello, should I create a NavigationViewController.swift file and copy the code?
Then how do I call it from the HostViewController?

**Comment by cagricolak** [comment]
thanks everyone I fix that

**Comment by okonor** [comment]
The new version is planned to be out at the end of the next week.

**Comment by Recouse** [comment]
@okonor Probably hasn’t added support NavigationController.
