### ISSUE TITLE
 showSideMenu() not working in UIViewController

### ISSUE THREAD

**Issue by HalitGumus** [handsomecode/InteractiveSideMenu#30]
if present storyboard in UIViewController showSideMenu() not working 

```
let presentAA = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "AA") as! AAViewController
        self.present(presentAA, animated: false, completion: nil)

```

```
//not working 
func menu() {
        showSideMenu()
}
```

**Comment by okonor** [comment]
Your *presentAA* ViewController should adopt `SideMenuItemContent` protocol. Does your *AAViewController* do it?

**Comment by HalitGumus** [comment]
`class AAViewController: UIViewController, SideMenuItemContent  {`

Yes doing

**Comment by HalitGumus** [comment]
```
public func showSideMenu() {
        if let menuContainerViewController = self.parent as? MenuContainerViewController {
            menuContainerViewController.showSideMenu()
        }else{
            dismiss(animated: false, completion: nil)
        }
    }
```
is falling to else

**Comment by okonor** [comment]
Do you use `self.present(presentAA, animated: false, completion: nil)` instead of `selectContentViewController(presentAA)`? If yes, it's the reason, because `selectContentViewController` method adds your VC as a child of `MenuContainerViewController`.

**Comment by HalitGumus** [comment]
present page AA ok. but fatalError 

```
 private func presentNavigationMenu() {
        if menuViewController == nil {
            fatalError("Invalid `menuViewController` value. It should not be nil")
        }
        self.present(menuViewController, animated: true, completion: nil)
    }
```

The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
fatal error: Invalid `menuViewController` value. It should not be nil: file /Users/AA/Pods/InteractiveSideMenu/Sources/MenuContainerViewController.swift, line 148

**Comment by okonor** [comment]
Do you initialize `menuViewController` like in Sample?

```swift
// Instantiate menu view controller by identifier
self.menuViewController = self.storyboard!.instantiateViewController(withIdentifier: "NavigationMenu") as! MenuViewController
```

**Comment by HalitGumus** [comment]
Yes i am initialize on the first page

**Comment by HalitGumus** [comment]
How to change content view, choose desired content controller in other page -> custom button

**Comment by okonor** [comment]
Please, send part of code, where you are initializing `MenuContainerViewController.menuViewController` value with all the details: file, method and so on. Or you can attach the project zip.

Now all we know is that `menuViewController` is nil.

Changing content view looks OK.

**Comment by HalitGumus** [comment]
[AA.zip](https://github.com/handsomecode/InteractiveSideMenu/files/1161594/AA.zip)

An example

**Comment by HalitGumus** [comment]
Help please
How can i solve

**Comment by okonor** [comment]
Hi @HalitGumus,

I've created a project with your files, commented or removed code that wasn't working. And updated your `NavigationMenuViewControler` with `NavigationMenuViewControler` from [the Sample](https://github.com/handsomecode/InteractiveSideMenu/tree/master/Sample/Sample). Side menu works fine. Please, see [the demo](https://d3vv6lp55qjaqc.cloudfront.net/items/3w1y3o2i3i1B430a1715/Screen%20Recording%202017-07-22%20at%2010.57%20PM.gif?X-CloudApp-Visitor-Id=1246883&v=7cbae89f).

You can take a look into the [resulting project](https://cl.ly/4042113M3s2s).

Best wishes, Olga.

**Comment by HalitGumus** [comment]
![aa](https://user-images.githubusercontent.com/17872594/28510657-4e17c47a-7052-11e7-94ed-5c0da8085a8e.gif)

My project already doing this action but i want to that when users push the button(Push Page BB) go to the BBViewController SideMenu does not work in (BBViewController)

**Comment by okonor** [comment]
You should use `selectContentViewController(presentAA)` instead of presenting ViewController even on `Push Page BB` button click. Otherwise, `MenuContainerViewController` won't know about your presented controller and won't be able to open/close menu.

If you need to add hierarchy to menu item, use UINavigationViewController as an menu item, and push controllers into it.

Hope, it'll help you.
