### ISSUE TITLE
Cant find SideMenuItemContent and TransitionOptions in InteractiveSideMenu

### ISSUE THREAD

**Issue by nemecence90** [handsomecode/InteractiveSideMenu#33]
I recently added InteractiveSideMenu through Cocoapods and I could not Set my UINavigationController protocol to SideMenuContent. And also to set the visible width I cannot see the TransitionOptions. Please Help!

I checked ChangeLogs and even forums, couldn't find any reference of anyone using it. Everyone uses the earlier version only. Even the changelog mentions use of TransitionOptions. How to go about it?

**Comment by AndreyArzhannikov** [comment]
Hi, @nemecence90!

`SideMenuItemContent` protocol and `TransitionOptions` struct are available since v2 of the library. 

So, please make sure that you have an updated version of the library. To do it, you can check your `Podfile.lock`. If it's not updated you need to run `pod update` command to install a new version. Perhaps, also, you need to update your spec repo: `pod repo update`. ([Related issue](https://github.com/handsomecode/InteractiveSideMenu/issues/5))

Thanks for your question!

**Comment by nemecence90** [comment]
Hi @AndreyArzhannikov, Thanks for the reply. 

Your suggestion worked and I was able to use SideMenuItemContent and TransitionOptions but now I am unable to use MenuItemContentViewController for the SubControllers in the Project.

![screen shot 2017-08-16 at 12 49 05 pm](https://user-images.githubusercontent.com/3805632/29351678-578a3678-8281-11e7-94c7-2a92d5281f01.png)

Can you please help with this?

**Comment by AndreyArzhannikov** [comment]
> I guess I will just use UIViewController in place of MenuItemContentViewController. Cause the protocol replaces the implementation of the MenuItemContentViewController.

@nemecence90 yes, you're correct. Also, you can take a look at [CHANGELOG](https://github.com/handsomecode/InteractiveSideMenu/blob/master/CHANGELOG.md) and [Sample] for a better understanding of library usage.

So, if your question has been resolved please close this issue.

**Comment by nemecence90** [comment]
Thanks for the support @AndreyArzhannikov. Also I would I like to support by contributing to the project. And i haven't contributed before, so its a first time for me. Can you help me how can I help with it?

**Comment by AndreyArzhannikov** [comment]
@nemecence90 Thanks!
So, we have two guidelines for contributing [CONTRIBUTING](https://github.com/handsomecode/InteractiveSideMenu/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/handsomecode/InteractiveSideMenu/blob/master/CODE_OF_CONDUCT.md). Please be familiar with it before contributing.

We'll add soon our Road Map for this library where you can see which features we would like to add.

Currently, feel free to send us pull requests with any changes related to bugfix and other changes you think would be useful for this project.

**Comment by nemecence90** [comment]
@AndreyArzhannikov Amazing! I would surely look into the details and see to it if I can find something to contribute to. Thanks for your support.

**Comment by AndreyArzhannikov** [comment]
That's awesome, thank you!
