### ISSUE TITLE
Unnecessary property `contentViewControllers`?

### ISSUE THREAD

**Issue by Dschee** [handsomecode/InteractiveSideMenu#39]
What's the point in setting the property `contentViewControllers`? I don't see where it is being used in your code – I don't need a list of all content view controllers for my app, therefore I'm curious: What's the reason for including it and is it really needed as stated in the README? Couldn't we simplify this library a bit by removing it?

**Comment by AndreyArzhannikov** [comment]
@Dschee At the moment, `contentViewControllers` is used only in client code like `NavigationMenuViewController` from [sample](https://github.com/handsomecode/InteractiveSideMenu/blob/2.0/Sample/Sample/NavigationMenuViewController.swift?utf8=%E2%9C%93#L70) for selecting menu item VC. 
So it looks a little weird and will be fixed after reworking and adding something like helper you suggested within in #40 .

Thanks for pointing at it.
