### ISSUE TITLE
Content turns white when menu open

### ISSUE THREAD

**Issue by seancrowe5** [handsomecode/InteractiveSideMenu#4]
In your animation, it shows the content from an itemViewController when the menu is open. In your Sample app and in my implementation the content disappears and you can only see a blank white view controller off to the side. I'm probably missing something simple to maintain the itemViewController content after it animates to the right. 

Edit: That was a worded poorly haha When we're looking at the Cat photo on the Sample App and we open the menu....why does the cat photo disappear? Is it possible to keep the cat photo when the menu is open?

**Comment by AndreyArzhannikov** [comment]
Hi @seancrowe5 

To show content when the menu is open you should use `menuTransitionOptionsBuilder()` and change `visibleContentWidth`.
Here's an example:
```swift
class HostViewController: MenuContainerViewController {
    //...
    override func menuTransitionOptionsBuilder() -> TransitionOptionsBuilder? {
        return TransitionOptionsBuilder() { builder in
            builder.duration = 0.5
            builder.contentScale = 1
            builder.visibleContentWidth = 50
        }
    }
}
```

If you use simulator iPhone 7 iOS 10.2 you can see that content view is white when the menu is open. It's really looks like a bug within iOS simulator, just try to use another version of simulator or real device. In such case It works as it has to.

Thanks for question! Feel free to send us pull requests!
