### ISSUE TITLE
install through CocoaPods -> Use of unresolved identifier 'TransitionOptions'

### ISSUE THREAD

**Issue by epitonium** [handsomecode/InteractiveSideMenu#41]
Just installed it through CocoaPods. Set my UIViewController to conform to MenuContainerViewController. And this XCode error appears: Use of unresolved identifier 'TransitionOptions'. And i couldn't find implementation for this in InteractiveSideMenu Pod classes. transitionOptions property is missing too. I compared the class MenuContainerViewController from Pod and from example from GitHub and they seem different! Could you please help me what am doing wrong?
<img width="2205" alt="screen shot 2017-08-30 at 19 37 28" src="https://user-images.githubusercontent.com/6273817/29884126-18c3f740-8dbb-11e7-92a7-db7754b8920b.png">

**Comment by okonor** [comment]
Hi @epitonium,

Please, take a look into [this issue](https://github.com/handsomecode/InteractiveSideMenu/issues/33). Maybe, it'll help you.

If no, we'll get into the details of your question a little bit later.

Thanks for using library and asking question.

**Comment by epitonium** [comment]
Thank you very much! This issue was already open and i missed it. Solved my problem!

**Comment by okonor** [comment]
Glad to hear! You're welcome.
