### ISSUE TITLE
Status Bar not properly calculated into the menu

### ISSUE THREAD

**Issue by Dschee** [handsomecode/InteractiveSideMenu#42]
I don't know what the issue is here, but in my project the menu doesn't go under the status bar up to the top of the screen. As an example see this (you can see that where the menu ends the background is black):

![simulator screen shot 31 08 2017 15 25 30](https://user-images.githubusercontent.com/6942160/29925688-65102d2a-8e61-11e7-8b02-f3d04ec77042.png)

**Comment by AndreyArzhannikov** [comment]
@Dschee Could you provide more details about your menu view hierarchy or simple sample with this issue? It would be helpful since we can't reproduce this issue. Checked on [sample](https://github.com/handsomecode/InteractiveSideMenu/tree/master/Sample) and it works correctly.
