### ISSUE TITLE
Width of the menu not has full screen width

### ISSUE THREAD

**Issue by Dschee** [handsomecode/InteractiveSideMenu#43]
In my project the width of the menu view controller doesn't change to the visible size. Instead it just keeps the full size of the screen as you can see on the label which gets cut. Also I've attached the view debugger rendering of the same screen where you can see that there should actually even be a checkmark which is being overlapped by the content view though. How would I deal with that?

![simulator screen shot 31 08 2017 15 25 30](https://user-images.githubusercontent.com/6942160/29925841-e8c88f36-8e61-11e7-8896-eaadccfe8fd3.png)
<img width="413" alt="bildschirmfoto 2017-08-31 um 15 33 23" src="https://user-images.githubusercontent.com/6942160/29925842-e8f7c81e-8e61-11e7-8035-56b74f478768.png">

**Comment by AndreyArzhannikov** [comment]
@Dschee Currently, client code is responsible for the full handling of menu view layout. Thus, you can fix it manually, for instance, by setting constraints for menu content view.

Possibly, handling insets based on visible content width is a good idea of how to improve library usage. 

Thanks for using the library and feel free to send pull requests with improvements.

**Comment by Dschee** [comment]
Hi @AndreyArzhannikov, thank you for your answers on the issues we've seen with this library. After using [AKSidemenu](https://github.com/dogo/AKSideMenu) first and having problems with it, we hoped for a better library with this one. But we saw that this is far away from production ready for other use cases than whatever your use case might be – our's is actually pretty straight forward but as you can see with this issue your library doesn't provide much help, most things still have to be managed manually. Thus we decided to write our own open source framework which we hope will be more flexible and easier to integrate than this one or AKSideMenu.

We were looking for something as easy and flexible as [MMDrawerController](https://github.com/mutualmobile/MMDrawerController) but written for Swift and with more beautiful animation possibilities. Let's see if we will be able to succeed but we'll try. Thank you anyways for your help!

**Comment by AndreyArzhannikov** [comment]
@Dschee Have a good luck with building own solution.
