### ISSUE TITLE
Row Current Selection like in the demo gif?

### ISSUE THREAD

**Issue by jackdem** [handsomecode/InteractiveSideMenu#50]
I wondered if there was the ability to add the custom row selection as seen in your demo gif on the home page? I wanted a colour block or something to indicate the currently visible viewController in the side menu. Not sure if this is a feature of the api or if this is handled in the tableview delegate methods?

**Comment by progn** [comment]
You can override `setSelected` and `setHighlighted` methods  for your subclass of `UITableViewCell`. Something like this: 
```swift
class MenuItemCell: UITableViewCell {
    @IBOutlet private weak var titleLabel: UILabel!

    override func setSelected(_ selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)

        setState(selected: selected)
    }

    override func setHighlighted(_ highlighted: Bool, animated: Bool) {
        super.setHighlighted(highlighted, animated: animated)

        setState(selected: highlighted)
    }

    private func setState(selected: Bool) {
        if selected {
            titleLabel.textColor = UIColor.yellow
        } else {
            titleLabel.textColor = UIColor.white
        }
    }
}
```

**Comment by jackdem** [comment]
thanks, however when I then toggle the menu again the row is no longer selected? does this method not retain the colouration to show the current item selected?

**Comment by enmiller** [comment]
@jackdem 
Im currently making some updates to the sample project to behave more like the demo gif.  However, even in the current form of the sample app, the menu table's row selection stays throughout.  Are you sure you aren't telling the table view to deselect the row in `tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)`?

e.g.
```
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    tableView.deselectRow(at: indexPath, animated: true)
}
```

**Comment by enmiller** [comment]
The sample project has been updated to better reflect the demo gif on the README.  I'm going to close this issue as I see it being resolved.

If you have further questions or issues about the selection state of the Side Menu table, feel free to re/open the issue.
