### ISSUE TITLE
How to disable Swipe from left -> Show menu gesture?

### ISSUE THREAD

**Issue by epitonium** [handsomecode/InteractiveSideMenu#51]
I need to show the menu only by clicking on the showMenuButton. Currently the user also can swipe and the menu will appear. How can i disable this functionality?

**Comment by okonor** [comment]
Hi @epitonium,

There is no option to disable swipe using InteractiveSideMenu public methods.

To do it you should load sources and remove these lines in `viewDidLoad` of `MenuContainerViewController`:

```Swift
let screenEdgePanRecognizer = UIScreenEdgePanGestureRecognizer(
target: navigationMenuTransitionDelegate.interactiveTransition,
action: #selector(MenuInteractiveTransition.handlePanPresentation(recognizer:)))
screenEdgePanRecognizer.edges = .left
view.addGestureRecognizer(screenEdgePanRecognizer)
```
It will disable swipe on menu opening.

If you also want to disable swipe on menu closing you should commit this line in `func finishTransition(currentPercentComplete)` of `MenuAnimator` class:

```Swift
if let panRecognizer = self.panRecognizer {
     contentSnapshotView.addGestureRecognizer(panRecognizer)
}
```
Thank you for your question, we'll think about implementing this option in a future release.

**Comment by iamhx** [comment]
Thanks for this. Was having an issue where my table view moves up, hindering my custom header section.

**Comment by makeitTim** [comment]
Enabling and disabling the swipe is a great feature.

When is modal is displayed that must be resolved, right now the user can just swipe to the menu to escape.
