### ISSUE TITLE
MenuContainerViewController dissappears after rotation from/to landscape orientation

### ISSUE THREAD

**Issue by calli23** [handsomecode/InteractiveSideMenu#55]
My ViewController that uses InteractiveSideMenue dissappears with a sinkhole animation to the ground. I didn't touch the code and installed v2.0. I tried some fixing in viewWillTransitionToSize but without success. Is it a known swift 4 issue?

My specs:

Xcode 9
iphone 7
iOS 11.0.1

**Comment by okonor** [comment]
Hi @calli23,

Could you reproduce the same issue on the [Sample](https://github.com/handsomecode/InteractiveSideMenu/tree/master/Sample)?

**Comment by okonor** [comment]
Does it happen every time?
