### ISSUE TITLE
Switching side menu to right side?

### ISSUE THREAD

**Issue by jackdem** [handsomecode/InteractiveSideMenu#56]
Is there a simple method to change the menu to come from screen right rather than screen left? 

I need it to be inverted to the default method 

Cheers

**Comment by juancarlosdmz** [comment]
same here

**Comment by okonor** [comment]
Hi guys,

Unfortunately, there is no right menu support now. This task has been already added to our ToDo list. Related issue is #6.

Thank you for your question.
