### ISSUE TITLE
Preserving the state of a view controller if it is currently selected

### ISSUE THREAD

**Issue by iamhx** [handsomecode/InteractiveSideMenu#59]
I want to preserve the state of my view controller if it is currently selected because all the data in my Table View will be gone when I tap on the menu item.

How do I get the current selected VC?

    guard let menuContainerViewController = self.menuContainerViewController else {
		return
	}
		
	if (self.view.superview! == menuContainerViewController.contentViewControllers[1]) {
			
		print("It is the current VC, do not selectContentViewController")
	}
	else {
			
		menuContainerViewController.selectContentViewController(menuContainerViewController.contentViewControllers[1])

	}
	menuContainerViewController.hideSideMenu()

**Comment by okonor** [comment]
Hi @iamhx,

You can save current view controller index and then get it using `menuContainerViewController.contentViewControllers` array.

Thank you for using InteractiveSideMenuLibrary.

**Comment by okonor** [comment]
If it doesn't help you, please, let us know.
