### ISSUE TITLE
Menu Opening Up on Swipe But Not On Clicking Button

### ISSUE THREAD

**Issue by abhimasand** [handsomecode/InteractiveSideMenu#60]
I am trying to open the Side Menu by clicking a button, but the menu isn't opening . I am using the showSideMenu() function, and also have the SideMenuItemContent Delegate present ,but the side view isn't coming .

**Comment by okonor** [comment]
Did you try Sample's implementation? Does it work for you?

Do you use some complex controllers structure or TabBar/NavigationBar controllers? Please, provide specific details.

**Comment by ValeriiVV** [comment]
I have the same issue: swiping works fine, but if I tried open the Side Menu by IBAction - it crashes. I don't know why, but my class doesn't even call the viewDidLoad, viewWillAppear and so on methods. But it show me everything I added in xib. So, when I click my UIButton - it crashes with:
2017-11-21 12:14:54.277441+0300 *****[5270:15335230] -[UIViewController showMenuButtonClicked:]: unrecognized selector sent to instance 0x7f86efd09d70

**Comment by chetanpanchal94** [comment]
i am also facing same problem on swipe menu is being opened but clicking on menu button does not open menu.

`
let selectViewController = self.storyboard?.instantiateViewController(withIdentifier: "ViewController")
        
        let navigationController = UINavigationController(rootViewController: selectViewController!)
        navigationController.navigationBar.isHidden = true
        
        let menuVC = self.storyboard?.instantiateViewController(withIdentifier: "MenuVC") as! MenuVC
        menuVC.selectContentViewController(selectViewController!)`

**Comment by enmiller** [comment]
@Mashex @ValeriiVV @chetanpanchal94 
Would any of you be willing to post additional information about the issues you are seeing?  The sample project is working both with swiping and with tapping the menu button on the content view controllers.  Without further insight into your issue or your implementation code, it's difficult to figure out what is going on in your application(s).

**Comment by FahadQuait** [comment]
There is some missing code in the cocoapod. I tried the sample application and it works fine! wonder why the code is not reflected to cocoapod.
 I have the same issue and there are no feedback to further describe the issue. I will try to copy the sample classes and update this issue.
