### ISSUE TITLE
We can't override the shadow of the HostViewController.

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [handsomecode/InteractiveSideMenu#61]

**Comment by enmiller** [comment]
@AlaeddineOuerteni Will be available in v2.2 which I hope to release soon

**Comment by enmiller** [comment]
@AlaeddineOuerteni Try using `2.2.1`.  I have added a property for `SideMenuItemShadow` that lets you globally customize the drop shadow of the content controllers.
