### ISSUE TITLE
Can't add corners to the screenshot of the the HostViewController when menu is opened.

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [handsomecode/InteractiveSideMenu#62]

**Comment by enmiller** [comment]
@AlaeddineOuerteni 
By corners, do you mean to round the corners?  Can you explain any further?

**Comment by AlaeddineOuerteni** [comment]
Yes @enmiller.

I want to change the cornerRadius of the layer of the screenshot imageView.

Is it possible ?

**Comment by enmiller** [comment]
v2.3.0 now has a property on n`SideMenuItemOptions` that will allow you to set the corner radius of the opened content item.

**Comment by AlaeddineOuerteni** [comment]
Great job @enmiller ;)
