### ISSUE TITLE
How can i move to other view without click on menu item?

### ISSUE THREAD

**Issue by vravath** [handsomecode/InteractiveSideMenu#7]

**Comment by okonor** [comment]
@vravath If you mean move from one view controller (FirstViewController in sample) to another view controller (SecondViewController) without menu opening, it's not possible now. If no, please, provide more details.
Thank you for your question. Feel free to send pull requests to us.

**Comment by vravath** [comment]
of curse, that is what i mean. but now i found solution on it by using notificationCenter to help so i can move from FirstViewController to SecondViewCountroller without clicking your menu. thank for your awesome library
