### ISSUE TITLE
Question about using with iPad SplitView

### ISSUE THREAD

**Issue by makeitTim** [handsomecode/InteractiveSideMenu#70]
Works great on iPhone!

When the same form-driven app is run on iPad I think it would make more sense to put the menu in the left SplitView. Has anybody done this before? How could this be done in clean way?

**Comment by enmiller** [comment]
This is similar to the feature request of #64 

The architecture of the library and the nature of how UISplitViewController works does not inherently allow this to work.  If you'd like to see this feature be implemented, we'd be happy to review any pull requests that are submitted.

**Comment by makeitTim** [comment]
Thanks for the response!

Yeah, I've been toying with it and came to the same conclusion --- the way InteractiveSideMenu manages the VC's just doesn't adapt to how UISplitViewController works, kind of overlapping but conflicting solutions. From what I can tell, it doesn't really make sense to use them together.

The right approach would be to customize the InteractiveSideMenu side menu to look a little more natural on iPad. If I come up with a good method I'll post it here.

**Comment by enmiller** [comment]
Please do! Appreciate the enthusiasm for ideas and to help out. 

I’ve got a few ideas for v3 for better memory management and the way the menu is managed. Hopefully some of the new ideas will make it easier to adapt to iPad and SplitViews

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by enmiller** [comment]
I'm going to close this issue and leave #64 open has a feature request.  Please direct any further updates or requests to that issue thread.
