### ISSUE TITLE
How can i pop to rootview ? is there Support for navigationcontroller ?

### ISSUE THREAD

**Issue by ketulbshah** [handsomecode/InteractiveSideMenu#8]
I have sign out button in side menu. when i click this button i want to pop to root view. How i can do this ?Kindly support asap. 

Thank you.
Smartberrry

**Comment by AndreyArzhannikov** [comment]
Hi, @ketulbshah 
Could you add more details about your questions?

**Comment by ketulbshah** [comment]
In details : What i want to is "like in normal application, first we open Login page then after signin we open side menu... and on signout button, again want to pop at rootview. ...

I got solution...i have to dismiss menu then i have to call poptorootview for go to rootview of navigation 

 self.dismiss(animated: false, completion: nil)
   _ = self.nav?.popToRootViewController(animated: true)

**Comment by AndreyArzhannikov** [comment]
@ketulbshah Thanks for sharing specific details and describing your solution!

So feel free send us pull requests with improvements! 😉
