### ISSUE TITLE
Page Size Issues After Rotating with Left Menu Opened/Closed

### ISSUE THREAD

**Issue by xixinjie** [handsomecode/InteractiveSideMenu#85]
Hi @enmiller @AlexKorovyansky, thank you for sharing this awesome lib. Could you please help me solve the page size issues after rotating. Two cases as below:

**Case 1. Rotate with left menu closed**
1. Open my app in portrait, and open left menu to check its size: OK
2. Close left menu and rotate to landscape, open left menu to check its size: Error, a gap in bottom
3. Close left menu and rotate to portrait, open left menu to check its size: Error, a gap in bottom

**Case 2. Rotate with left menu opened**
1. Open my app in portrait, and open left menu to check its size: OK
2. Rotate to landscape, check main content page size: Error, a half-screen gap in right, open left menu to check its size: Error, a gap in bottom

It might be caused status bar or size control when rotate.

**Comment by xixinjie** [comment]
Closed this issue cuz I solved it, which is due to UINavigationController problem.

**Comment by vaibhav-varshaaweblabs** [comment]
@xixinjie Please share the solution here
