### ISSUE TITLE
How to remove damping effect?

### ISSUE THREAD

**Issue by stealdre** [handsomecode/InteractiveSideMenu#9]
Hi, I want to remove the damping effect in the open and close animations. How can I only set curveEaseOut animation for both? Thanks

**Comment by okonor** [comment]
You should set `useFinishingSpringOption` and `useCancelingSpringOption` of *TransitionOptionsBuilder* to **false** and set `animationOptions` to desired one. It's `.curveEaseInOut` by default.

It'll look like this
```
override func menuTransitionOptionsBuilder() -> TransitionOptionsBuilder? {
        return TransitionOptionsBuilder() { builder in
            builder.useFinishingSpringOption = false
            builder.useCancelingSpringOption = false
            builder.animationOptions = .curveEaseOut
        }
    }
```
You can find more details, concerning menu implementation, into the documentation.

**Comment by stealdre** [comment]
great! thanks a lot!
